services:
  kibana:
    image: docker.elastic.co/kibana/kibana:8.14.3
    container_name: kibana
    environment:
      ELASTICSEARCH_HOSTS: '["http://elasticsearch:9200"]'
    ports:
      - "55601:5601"
    networks:
      - elastic
    volumes:
      - kibana-data:/usr/share/kibana/data

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.14.3
    container_name: elasticsearch
    ports:
      - 9200:9200
      - 9300:9300
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
    volumes:
      - elasticsearch-data:/usr/share/elasticsearch/data
    networks:
      - elastic
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536

  grafana:
    image: grafana/grafana-oss:latest
    ports:
      - "53000:3000"
    networks:
      - elastic
    restart: unless-stopped
    volumes:
      - grafana-storage:/var/lib/grafana

networks:
  elastic:
volumes:
  elasticsearch-data:
  kibana-data:
  grafana-storage: